package net.momirealms.sparrow.yaml.serializer.builder;

import java.util.List;
import java.util.Objects;

/**
 * mapping builder, 通过字段 group 拼装对象 serializer.
 */
public final class MappingBuilder<T> {
    private final Class<T> type; // group 最终构造出的 Java 类型

    public MappingBuilder(Class<T> type) {
        this.type = Objects.requireNonNull(type, "type");
    }

    public <A> NodeSerializerGroups.Group1<T, A> group(FieldComponent<T, A> a) { return new NodeSerializerGroups.Group1<>(type, true, List.of(a)); }
    public <A, B> NodeSerializerGroups.Group2<T, A, B> group(FieldComponent<T, A> a, FieldComponent<T, B> b) { return new NodeSerializerGroups.Group2<>(type, true, List.of(a, b)); }
    public <A, B, C> NodeSerializerGroups.Group3<T, A, B, C> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c) { return new NodeSerializerGroups.Group3<>(type, true, List.of(a, b, c)); }
    public <A, B, C, D> NodeSerializerGroups.Group4<T, A, B, C, D> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d) { return new NodeSerializerGroups.Group4<>(type, true, List.of(a, b, c, d)); }
    public <A, B, C, D, E> NodeSerializerGroups.Group5<T, A, B, C, D, E> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e) { return new NodeSerializerGroups.Group5<>(type, true, List.of(a, b, c, d, e)); }
    public <A, B, C, D, E, F> NodeSerializerGroups.Group6<T, A, B, C, D, E, F> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f) { return new NodeSerializerGroups.Group6<>(type, true, List.of(a, b, c, d, e, f)); }
    public <A, B, C, D, E, F, G> NodeSerializerGroups.Group7<T, A, B, C, D, E, F, G> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f, FieldComponent<T, G> g) { return new NodeSerializerGroups.Group7<>(type, true, List.of(a, b, c, d, e, f, g)); }
    public <A, B, C, D, E, F, G, H> NodeSerializerGroups.Group8<T, A, B, C, D, E, F, G, H> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f, FieldComponent<T, G> g, FieldComponent<T, H> h) { return new NodeSerializerGroups.Group8<>(type, true, List.of(a, b, c, d, e, f, g, h)); }
    public <A, B, C, D, E, F, G, H, I> NodeSerializerGroups.Group9<T, A, B, C, D, E, F, G, H, I> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f, FieldComponent<T, G> g, FieldComponent<T, H> h, FieldComponent<T, I> i) { return new NodeSerializerGroups.Group9<>(type, true, List.of(a, b, c, d, e, f, g, h, i)); }
    public <A, B, C, D, E, F, G, H, I, J> NodeSerializerGroups.Group10<T, A, B, C, D, E, F, G, H, I, J> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f, FieldComponent<T, G> g, FieldComponent<T, H> h, FieldComponent<T, I> i, FieldComponent<T, J> j) { return new NodeSerializerGroups.Group10<>(type, true, List.of(a, b, c, d, e, f, g, h, i, j)); }
    public <A, B, C, D, E, F, G, H, I, J, K> NodeSerializerGroups.Group11<T, A, B, C, D, E, F, G, H, I, J, K> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f, FieldComponent<T, G> g, FieldComponent<T, H> h, FieldComponent<T, I> i, FieldComponent<T, J> j, FieldComponent<T, K> k) { return new NodeSerializerGroups.Group11<>(type, true, List.of(a, b, c, d, e, f, g, h, i, j, k)); }
    public <A, B, C, D, E, F, G, H, I, J, K, L> NodeSerializerGroups.Group12<T, A, B, C, D, E, F, G, H, I, J, K, L> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f, FieldComponent<T, G> g, FieldComponent<T, H> h, FieldComponent<T, I> i, FieldComponent<T, J> j, FieldComponent<T, K> k, FieldComponent<T, L> l) { return new NodeSerializerGroups.Group12<>(type, true, List.of(a, b, c, d, e, f, g, h, i, j, k, l)); }
    public <A, B, C, D, E, F, G, H, I, J, K, L, M> NodeSerializerGroups.Group13<T, A, B, C, D, E, F, G, H, I, J, K, L, M> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f, FieldComponent<T, G> g, FieldComponent<T, H> h, FieldComponent<T, I> i, FieldComponent<T, J> j, FieldComponent<T, K> k, FieldComponent<T, L> l, FieldComponent<T, M> m) { return new NodeSerializerGroups.Group13<>(type, true, List.of(a, b, c, d, e, f, g, h, i, j, k, l, m)); }
    public <A, B, C, D, E, F, G, H, I, J, K, L, M, N> NodeSerializerGroups.Group14<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f, FieldComponent<T, G> g, FieldComponent<T, H> h, FieldComponent<T, I> i, FieldComponent<T, J> j, FieldComponent<T, K> k, FieldComponent<T, L> l, FieldComponent<T, M> m, FieldComponent<T, N> n) { return new NodeSerializerGroups.Group14<>(type, true, List.of(a, b, c, d, e, f, g, h, i, j, k, l, m, n)); }
    public <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> NodeSerializerGroups.Group15<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f, FieldComponent<T, G> g, FieldComponent<T, H> h, FieldComponent<T, I> i, FieldComponent<T, J> j, FieldComponent<T, K> k, FieldComponent<T, L> l, FieldComponent<T, M> m, FieldComponent<T, N> n, FieldComponent<T, O> o) { return new NodeSerializerGroups.Group15<>(type, true, List.of(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o)); }
    public <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> NodeSerializerGroups.Group16<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> group(FieldComponent<T, A> a, FieldComponent<T, B> b, FieldComponent<T, C> c, FieldComponent<T, D> d, FieldComponent<T, E> e, FieldComponent<T, F> f, FieldComponent<T, G> g, FieldComponent<T, H> h, FieldComponent<T, I> i, FieldComponent<T, J> j, FieldComponent<T, K> k, FieldComponent<T, L> l, FieldComponent<T, M> m, FieldComponent<T, N> n, FieldComponent<T, O> o, FieldComponent<T, P> p) { return new NodeSerializerGroups.Group16<>(type, true, List.of(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p)); }
}
