package net.momirealms.sparrow.yaml.serializer.builder;

import java.util.List;
import java.util.Objects;

/**
 * sequence builder, 通过元素 group 拼装对象 serializer.
 */
public final class SequenceBuilder<T> {
    private final Class<T> type; // group 最终构造出的 Java 类型

    public SequenceBuilder(Class<T> type) {
        this.type = Objects.requireNonNull(type, "type");
    }

    public <A> NodeSerializerGroups.Group1<T, A> group(ElementComponent<T, A> a) { return new NodeSerializerGroups.Group1<>(type, false, List.of(a)); }
    public <A, B> NodeSerializerGroups.Group2<T, A, B> group(ElementComponent<T, A> a, ElementComponent<T, B> b) { return new NodeSerializerGroups.Group2<>(type, false, List.of(a, b)); }
    public <A, B, C> NodeSerializerGroups.Group3<T, A, B, C> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c) { return new NodeSerializerGroups.Group3<>(type, false, List.of(a, b, c)); }
    public <A, B, C, D> NodeSerializerGroups.Group4<T, A, B, C, D> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d) { return new NodeSerializerGroups.Group4<>(type, false, List.of(a, b, c, d)); }
    public <A, B, C, D, E> NodeSerializerGroups.Group5<T, A, B, C, D, E> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e) { return new NodeSerializerGroups.Group5<>(type, false, List.of(a, b, c, d, e)); }
    public <A, B, C, D, E, F> NodeSerializerGroups.Group6<T, A, B, C, D, E, F> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f) { return new NodeSerializerGroups.Group6<>(type, false, List.of(a, b, c, d, e, f)); }
    public <A, B, C, D, E, F, G> NodeSerializerGroups.Group7<T, A, B, C, D, E, F, G> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f, ElementComponent<T, G> g) { return new NodeSerializerGroups.Group7<>(type, false, List.of(a, b, c, d, e, f, g)); }
    public <A, B, C, D, E, F, G, H> NodeSerializerGroups.Group8<T, A, B, C, D, E, F, G, H> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f, ElementComponent<T, G> g, ElementComponent<T, H> h) { return new NodeSerializerGroups.Group8<>(type, false, List.of(a, b, c, d, e, f, g, h)); }
    public <A, B, C, D, E, F, G, H, I> NodeSerializerGroups.Group9<T, A, B, C, D, E, F, G, H, I> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f, ElementComponent<T, G> g, ElementComponent<T, H> h, ElementComponent<T, I> i) { return new NodeSerializerGroups.Group9<>(type, false, List.of(a, b, c, d, e, f, g, h, i)); }
    public <A, B, C, D, E, F, G, H, I, J> NodeSerializerGroups.Group10<T, A, B, C, D, E, F, G, H, I, J> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f, ElementComponent<T, G> g, ElementComponent<T, H> h, ElementComponent<T, I> i, ElementComponent<T, J> j) { return new NodeSerializerGroups.Group10<>(type, false, List.of(a, b, c, d, e, f, g, h, i, j)); }
    public <A, B, C, D, E, F, G, H, I, J, K> NodeSerializerGroups.Group11<T, A, B, C, D, E, F, G, H, I, J, K> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f, ElementComponent<T, G> g, ElementComponent<T, H> h, ElementComponent<T, I> i, ElementComponent<T, J> j, ElementComponent<T, K> k) { return new NodeSerializerGroups.Group11<>(type, false, List.of(a, b, c, d, e, f, g, h, i, j, k)); }
    public <A, B, C, D, E, F, G, H, I, J, K, L> NodeSerializerGroups.Group12<T, A, B, C, D, E, F, G, H, I, J, K, L> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f, ElementComponent<T, G> g, ElementComponent<T, H> h, ElementComponent<T, I> i, ElementComponent<T, J> j, ElementComponent<T, K> k, ElementComponent<T, L> l) { return new NodeSerializerGroups.Group12<>(type, false, List.of(a, b, c, d, e, f, g, h, i, j, k, l)); }
    public <A, B, C, D, E, F, G, H, I, J, K, L, M> NodeSerializerGroups.Group13<T, A, B, C, D, E, F, G, H, I, J, K, L, M> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f, ElementComponent<T, G> g, ElementComponent<T, H> h, ElementComponent<T, I> i, ElementComponent<T, J> j, ElementComponent<T, K> k, ElementComponent<T, L> l, ElementComponent<T, M> m) { return new NodeSerializerGroups.Group13<>(type, false, List.of(a, b, c, d, e, f, g, h, i, j, k, l, m)); }
    public <A, B, C, D, E, F, G, H, I, J, K, L, M, N> NodeSerializerGroups.Group14<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f, ElementComponent<T, G> g, ElementComponent<T, H> h, ElementComponent<T, I> i, ElementComponent<T, J> j, ElementComponent<T, K> k, ElementComponent<T, L> l, ElementComponent<T, M> m, ElementComponent<T, N> n) { return new NodeSerializerGroups.Group14<>(type, false, List.of(a, b, c, d, e, f, g, h, i, j, k, l, m, n)); }
    public <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> NodeSerializerGroups.Group15<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f, ElementComponent<T, G> g, ElementComponent<T, H> h, ElementComponent<T, I> i, ElementComponent<T, J> j, ElementComponent<T, K> k, ElementComponent<T, L> l, ElementComponent<T, M> m, ElementComponent<T, N> n, ElementComponent<T, O> o) { return new NodeSerializerGroups.Group15<>(type, false, List.of(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o)); }
    public <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> NodeSerializerGroups.Group16<T, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> group(ElementComponent<T, A> a, ElementComponent<T, B> b, ElementComponent<T, C> c, ElementComponent<T, D> d, ElementComponent<T, E> e, ElementComponent<T, F> f, ElementComponent<T, G> g, ElementComponent<T, H> h, ElementComponent<T, I> i, ElementComponent<T, J> j, ElementComponent<T, K> k, ElementComponent<T, L> l, ElementComponent<T, M> m, ElementComponent<T, N> n, ElementComponent<T, O> o, ElementComponent<T, P> p) { return new NodeSerializerGroups.Group16<>(type, false, List.of(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p)); }
}
